packageExtensions:
  '@docusaurus/theme-search-algolia@*':
    peerDependencies:
      '@algolia/client-search': '*'
      prism-react-renderer: '*'
    peerDependenciesMeta:
      '@algolia/client-search':
        optional: true
      prism-react-renderer:
        optional: true

  '@docsearch/react@*':
    peerDependencies:
      '@algolia/client-search': '*'
    peerDependenciesMeta:
      '@algolia/client-search':
        optional: true

  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '*'

  '@mdx-js/loader@*':
    peerDependencies:
      react: '*'
    peerDependenciesMeta:
      react:
        optional: true

  '@roots/bedrock@*':
    peerDependencies:
      tailwind: '*'

  '@yarnpkg/builder@*':
    peerDependencies:
      esbuild: '*'

  babel-plugin-jsx-dom-expressions@*:
    peerDependencies:
      '@babel-core': '*'
    peerDependenciesMeta:
      '@babel-core':
        optional: true

  babel-preset-solid@*:
    peerDependencies:
      '@babel-core': '*'
    peerDependenciesMeta:
      '@babel-core':
        optional: true

  example-emotion@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true

  example-markdown@*:
    peerDependencies:
      react: '*'
      react-dom: '*'

  example-react@*:
    peerDependencies:
      react: '*'
      react-dom: '*'

  example-sass@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
      sass: '*'
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      sass:
        optional: true

  example-solid@*:
    peerDependencies:
      '@babel-core': '*'
      solid-js: '*'
    peerDependenciesMeta:
      '@babel-core':
        optional: true
      solid-js:
        optional: true

  example-tailwindcss@*:
    peerDependencies:
      autoprefixer: '*'
    peerDependenciesMeta:
      autoprefixer:
        optional: true

  react-dev-utils@*:
    peerDependencies:
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      typescript:
        optional: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - .yarn/local/bundles/@yarnpkg/plugin-kjo.js

yarnPath: .yarn/releases/yarn-3.0.1.cjs
