version: '3.2'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873

  bud:
    build: ./dev/build
    container_name: bud
    depends_on:
      - verdaccio
    networks:
      - node-network
    working_dir: /bud
    user: node
    command: bash -c /bud/dev/build/init.sh
    volumes:
      - ./:/bud
      - ./dev/build/.yarnrc.yml:/bud/.yarnrc.yml
      - ./dev/build/.npmrc:/bud/.npmrc

volumes:
  bud:

networks:
  node-network:
    driver: bridge
