[build]
  publish = "build/"

  # Default build command.
  command = "yarn kjo build && yarn kjo gen"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
