version: '3'
services:
  app:
    build: ./config/docker/php-fpm
    restart: always
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mariadb
      WP_ENV: development
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
    volumes:
      - ./:/bedrock

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  redis:
    image: redis
    restart: always

  nginx:
    image: nginx
    restart: always
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/bedrock
      - ./config/docker/nginx/conf.d:/etc/nginx/conf.d
