name: test (unit)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        node:
          - 20.8.0

    name: unit test (node@v${{matrix.node}}/${{matrix.platform}})
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          cache: yarn

      - run: yarn

      - run: yarn @bud test unit
